import type { Metadata } from "next";

import "~/styles/global.css";

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased">{children}</body>
		</html>
	);
}
