import type { Metadata } from "next";

import "~/styles/global.css";

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default function RootLayout(props: LayoutProps<"/">) {
	return (
		<html lang="en">
			<body className="antialiased">{props.children}</body>
		</html>
	);
}
